-- ============================================================
-- Migration: M01 PR Amendment Entry
-- Adds columns required by the Amendment SPs.
-- Safe to re-run (IF NOT EXISTS guards on every ALTER).
-- Run BEFORE executing the amendment stored procedures.
-- Target: SpinRiseSaranya
-- ============================================================

-- PO_APRH: concurrency token
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'PO_APRH' AND COLUMN_NAME = 'row_version')
    ALTER TABLE dbo.PO_APRH ADD row_version ROWVERSION;
GO

-- PO_APRH: audit trail for who created each amendment
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'PO_APRH' AND COLUMN_NAME = 'createdby')
    ALTER TABLE dbo.PO_APRH ADD createdby VARCHAR(50) NULL;
GO

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'PO_APRH' AND COLUMN_NAME = 'createddt')
    ALTER TABLE dbo.PO_APRH ADD createddt VARCHAR(25) NULL;
GO

-- PO_APRH: header snapshot for 2nd+ amendments (PO_PRH deleted after first)
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'PO_APRH' AND COLUMN_NAME = 'depcode')
    ALTER TABLE dbo.PO_APRH ADD depcode VARCHAR(3) NULL;
GO

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'PO_APRH' AND COLUMN_NAME = 'REQNAME')
    ALTER TABLE dbo.PO_APRH ADD REQNAME VARCHAR(25) NULL;
GO

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'PO_APRH' AND COLUMN_NAME = 'SECTION')
    ALTER TABLE dbo.PO_APRH ADD SECTION VARCHAR(20) NULL;
GO

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'PO_APRH' AND COLUMN_NAME = 'ITYPE')
    ALTER TABLE dbo.PO_APRH ADD ITYPE CHAR(1) NULL;
GO

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'PO_APRH' AND COLUMN_NAME = 'PLACEOFISS')
    ALTER TABLE dbo.PO_APRH ADD PLACEOFISS VARCHAR(30) NULL;
GO

-- PO_APRL: rate origin tracking (ORIGINAL / MANUAL)
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'PO_APRL' AND COLUMN_NAME = 'RATE_SOURCE')
    ALTER TABLE dbo.PO_APRL ADD RATE_SOURCE VARCHAR(20) NULL;
GO

-- PO_APRL: justification required when RATE_SOURCE = 'MANUAL'
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'PO_APRL' AND COLUMN_NAME = 'RATE_JUSTIFICATION')
    ALTER TABLE dbo.PO_APRL ADD RATE_JUSTIFICATION VARCHAR(200) NULL;
GO

-- PO_APRL: stock snapshot at time of amendment
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'PO_APRL' AND COLUMN_NAME = 'curstock')
    ALTER TABLE dbo.PO_APRL ADD curstock NUMERIC(12,3) NULL;
GO

-- PO_APRL: FSD v2.3 additional line fields
IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'PO_APRL' AND COLUMN_NAME = 'CATCODE')
    ALTER TABLE dbo.PO_APRL ADD CATCODE VARCHAR(1) NULL;
GO

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'PO_APRL' AND COLUMN_NAME = 'BGRPCODE')
    ALTER TABLE dbo.PO_APRL ADD BGRPCODE VARCHAR(4) NULL;
GO

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'PO_APRL' AND COLUMN_NAME = 'PLACE')
    ALTER TABLE dbo.PO_APRL ADD PLACE VARCHAR(40) NULL;
GO

IF NOT EXISTS (
    SELECT 1 FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_NAME = 'PO_APRL' AND COLUMN_NAME = 'APPCOST')
    ALTER TABLE dbo.PO_APRL ADD APPCOST NUMERIC(11,2) NULL;
GO

-- PO_PRINT_LOG: audit trail for amendment print events (FSD §6 DB Migration)
-- Tracks first print vs reprint; required for REPRINT_FLG permission control.
IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE name = 'PO_PRINT_LOG' AND type = 'U')
BEGIN
    CREATE TABLE dbo.PO_PRINT_LOG (
        id           INT IDENTITY(1,1)  PRIMARY KEY,
        divcode      VARCHAR(10)        NOT NULL,
        prno         NUMERIC(6,0)       NOT NULL,
        amendno      INT                NOT NULL,
        amenddate    DATE               NOT NULL,
        printed_by   VARCHAR(50)        NOT NULL,
        printed_on   DATETIME           NOT NULL DEFAULT GETDATE(),
        reprint_flag CHAR(1)            NOT NULL DEFAULT 'N'
    );
END
GO
