<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SpinRise.QuestPDF.DateWise</RootNamespace>
    <AssemblyName>SpinRise.QuestPDF.DateWise</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="QuestPDF" Version="2025.1.0" />
    <PackageReference Include="Dapper" Version="2.1.66" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SpinRise.QuestPDF.Common\SpinRise.QuestPDF.Common.csproj" />
  </ItemGroup>
</Project>
