namespace Spinrise.Application.Areas.PurchaseOrder.Amendment.DTOs;

public record PrAmendmentPrintDto(
    string  DivCode,
    decimal PrNo,
    string  PrDate,
    int     AmendNo,
    string  AmendDate,
    string  AmendmentReason,
    string  RefNo,
    string  CreatedBy,
    string  DepCode,
    string  DepName,
    string  ReqName,
    string  DivName,
    string  DivPrintName,
    string  DivUnitName,
    string  DivAddress1,
    string  DivAddress2,
    string  DivAddress3,
    string  DivPinCode,
    string  DivState,
    string  DivPhone,
    string  DivEmail,
    byte[]? DivLogo,
    IReadOnlyList<PrAmendmentPrintLineDto> Lines
);

public record PrAmendmentPrintLineDto(
    long    SNo,
    decimal PrSno,
    string  ItemCode,
    string  ItemName,
    string  Uom,
    decimal QtyInd,
    string? ReqdDate,
    decimal CurStock,
    decimal Rate,
    decimal Value,
    string  RateSource,
    string  RateJustification,
    decimal QtyApproved,
    decimal QtyOrdered,
    decimal QtyReceived,
    string  MacNo,
    string  MacDesc,
    string  DrawNo,
    string  CatNo,
    string  CatCode,
    string  BgrpCode,
    string  Place,
    decimal AppCost,
    string  Remarks
);
