<Project>
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <Company>SpinRise</Company>
    <Product>SpinRise QuestPDF Reports</Product>
    <Copyright>Copyright (c) Kalsofte</Copyright>
  </PropertyGroup>
</Project>
