<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>SpinRise.QuestPDF.Common</RootNamespace>
    <AssemblyName>SpinRise.QuestPDF.Common</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.SqlClient" Version="5.1.6" />
    <PackageReference Include="QuestPDF" Version="2025.1.0" />
  </ItemGroup>
</Project>
